// Business emails found by web research, keyed by business id.
// Generated by api/build-emails.ps1 from api/email-batches/results-*.txt
// Kept separate from places-data.js so a data refresh never wipes emails.
const EMAIL_OVERRIDES = {};
