// Owner names found by web research, keyed by business id.
// Generated by api/build-owners.ps1 from api/owner-batches/results-*.txt
// Kept separate from places-data.js so a data refresh never wipes owners.
const OWNER_OVERRIDES = {};
