# Aggregates email research results (api/email-batches/results-*.txt)
# into admin/emails-data.js for the Webnara admin frontend.
# Format per line: businessId<TAB>email<TAB>source

$batchDir = Join-Path $PSScriptRoot 'email-batches'
$emails = [ordered]@{}

Get-ChildItem (Join-Path $batchDir 'results-*.txt') -ErrorAction SilentlyContinue | ForEach-Object {
    foreach ($line in (Get-Content $_.FullName -Encoding UTF8)) {
        $parts = $line -split "`t"
        if ($parts.Count -lt 2) { continue }
        $id = $parts[0].Trim()
        $email = $parts[1].Trim().ToLower()
        $source = if ($parts.Count -ge 3) { $parts[2].Trim() } else { '' }
        if ($id -and $email -match '^[^\s@]+@[^\s@]+\.[^\s@]+$') {
            $emails[$id] = @{ email = $email; source = $source }
        }
    }
}

$json = ConvertTo-Json -InputObject $emails -Depth 3 -Compress
if ($emails.Count -eq 0) { $json = '{}' }

$dest = Join-Path (Split-Path $PSScriptRoot -Parent) 'admin\emails-data.js'
$content = "// Business emails found by web research, keyed by business id.`n// Generated by api/build-emails.ps1 from api/email-batches/results-*.txt`n// Kept separate from places-data.js so a data refresh never wipes emails.`nconst EMAIL_OVERRIDES = $json;`n"
[System.IO.File]::WriteAllText($dest, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $($emails.Count) emails to admin\emails-data.js"
