# Aggregates owner research results (api/owner-batches/results-*.txt)
# into admin/owners-data.js for the WebGap frontend.

$batchDir = Join-Path $PSScriptRoot 'owner-batches'
$owners = [ordered]@{}

Get-ChildItem (Join-Path $batchDir 'results-*.txt') -ErrorAction SilentlyContinue | ForEach-Object {
    foreach ($line in (Get-Content $_.FullName -Encoding UTF8)) {
        $parts = $line -split "`t"
        if ($parts.Count -lt 2) { continue }
        $id = $parts[0].Trim()
        $name = $parts[1].Trim()
        $source = if ($parts.Count -ge 3) { $parts[2].Trim() } else { '' }
        if ($id -and $name) {
            $owners[$id] = @{ name = $name; source = $source }
        }
    }
}

$json = ConvertTo-Json -InputObject $owners -Depth 3 -Compress
if ($owners.Count -eq 0) { $json = '{}' }

$dest = Join-Path (Split-Path $PSScriptRoot -Parent) 'admin\owners-data.js'
$content = "// Owner names found by web research, keyed by business id.`n// Generated by api/build-owners.ps1 from api/owner-batches/results-*.txt`n// Kept separate from places-data.js so a data refresh never wipes owners.`nconst OWNER_OVERRIDES = $json;`n"
[System.IO.File]::WriteAllText($dest, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $($owners.Count) owners to admin\owners-data.js"
