function Get-PlacesDataPath {
    Join-Path (Split-Path $PSScriptRoot -Parent) 'admin\places-data.js'
}

function Get-PlacesCachePath {
    Join-Path $PSScriptRoot 'places-cache.json'
}

function ConvertTo-Hashtable {
    param($Item)

    if ($null -eq $Item) { return $null }
    if ($Item -is [System.Collections.IDictionary]) {
        $copy = @{}
        foreach ($key in $Item.Keys) { $copy[$key] = $Item[$key] }
        return $copy
    }

    $row = @{}
    $Item.PSObject.Properties | ForEach-Object { $row[$_.Name] = $_.Value }
    return $row
}

function Get-BusinessId {
    param($Business)
    if ($null -eq $Business) { return $null }
    if ($Business -is [System.Collections.IDictionary]) {
        if ($Business.Contains('id') -and $Business['id']) { return [string]$Business['id'] }
        return $null
    }
    if ($Business.PSObject.Properties.Match('id').Count -gt 0 -and $Business.id) {
        return [string]$Business.id
    }
    return $null
}

function Read-PlacesJson {
    param([string]$JsonText)

    if (-not $JsonText) { return @() }

    $raw = $JsonText | ConvertFrom-Json
    $items = @()

    if ($raw -is [System.Collections.IList] -and -not ($raw -is [string])) {
        $items = @($raw)
    } elseif ($null -ne $raw.value) {
        $items = @($raw.value)
    } else {
        $items = @($raw)
    }

    $rows = New-Object System.Collections.Generic.List[object]
    foreach ($item in $items) {
        if ($null -eq $item) { continue }
        $row = ConvertTo-Hashtable $item
        if (Get-BusinessId $row) {
            [void]$rows.Add($row)
        }
    }
    return [object[]]$rows.ToArray()
}

function Read-PlacesCache {
    $cachePath = Get-PlacesCachePath
    if (Test-Path $cachePath) {
        return @(Read-PlacesJson (Get-Content $cachePath -Raw -Encoding UTF8))
    }

    # Migrate from legacy places-data.js once
    $legacyPath = Get-PlacesDataPath
    if (-not (Test-Path $legacyPath)) { return @() }

    $content = Get-Content $legacyPath -Raw -Encoding UTF8
    if ($content -notmatch 'const GOOGLE_BUSINESSES = (\[[\s\S]*\]);') {
        return @()
    }

    return @(Read-PlacesJson $Matches[1])
}

function Read-PlacesBusinesses {
    Read-PlacesCache
}

function Write-PlacesCache {
    param(
        [Parameter(Mandatory = $true)]
        $Businesses,
        [string]$HeaderNote = 'api/fetch-places.ps1'
    )

    $cachePath = Get-PlacesCachePath
    $backupPath = "$cachePath.bak"

    if (Test-Path $cachePath) {
        Copy-Item $cachePath $backupPath -Force
    }

    $rows = @($Businesses | ForEach-Object { ConvertTo-Hashtable $_ } | Where-Object { Get-BusinessId $_ })
    $sorted = [object[]]($rows | Sort-Object { $_.name })
    $json = ConvertTo-Json -InputObject $sorted -Depth 8 -Compress

    # ConvertTo-Json sometimes wraps arrays as {"value":[...]} — unwrap for a real JSON array file
    if ($json -match '^\{"value":(\[[\s\S]*\]),"Count":') {
        $json = $Matches[1]
    }

    [System.IO.File]::WriteAllText($cachePath, $json, (New-Object System.Text.UTF8Encoding($false)))

    $jsPath = Get-PlacesDataPath
    $header = "// Generated by $HeaderNote on $((Get-Date).ToString('yyyy-MM-dd HH:mm'))`n// Every business: operating, has a phone, NO website on its Google profile.`n"
    [System.IO.File]::WriteAllText($jsPath, $header + "const GOOGLE_BUSINESSES = $json;`n", (New-Object System.Text.UTF8Encoding($false)))
}

function Write-PlacesBusinesses {
    param(
        [Parameter(Mandatory = $true)]
        $Businesses,
        [string]$Path, # ignored; kept for compatibility
        [string]$HeaderNote = 'api/fetch-places.ps1'
    )

    Write-PlacesCache -Businesses $Businesses -HeaderNote $HeaderNote
}

function Get-PlaceKey {
    param([string]$BusinessId)
    if ($BusinessId -like 'gp-*') { return $BusinessId.Substring(3) }
    return $BusinessId
}
